# Iosevka Extended
# ================

[buildPlans.iosevka-extended]
family = "Iosevka Extended"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-extended.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-extended.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-extended.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-extended.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-extended.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"

# Iosevka Aile Extended
# =====================

[buildPlans.iosevka-aile-extended]
family = "Iosevka Aile Extended"
spacing = "quasi-proportional"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-aile-extended.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-aile-extended.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-aile-extended.widths.normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.iosevka-aile-extended.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-aile-extended.slopes.oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"
